language: java
jdk:
  - openjdk11

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'

script:  "./mvnw clean package"

before_install:
  - chmod +x mvnw

notifications:
  email:
    recipients:
      - process0823@gmail.com