language: java
jdk:
  - openjdk11

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'

script:  "./mvnw clean package"

before_install:
  - chmod +x mvnw

before_deploy:
  - zip -r lanoa *
  - mkdir -p deploy
  - mv lanoa.zip deploy/lanoa.zip

deploy:
    - provider: s3
      access_key_id: $AWS_ACCESS_KEY
      secret_access_key: $AWS_SECRET_KEY
      bucket: lanoa-deploy
      region: ap-northeast-2
      skip_cleanup: true
      acl: public_read
      local_dir: deploy
      wait-until-deployed: true
      on:
        repo: TAEIN888/lanoa
        branch: master

    - provider: codedeploy
      access_key_id: $AWS_ACCESS_KEY
      secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
      bucket: lanoa-deploy # S3 버킷
      key: lanoa.zip # 빌드 파일을 압축해서 전달
      bundle_type: zip
      application: lanoa # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
      deployment_group: lanoa # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
      region: ap-northeast-2
      wait-until-deployed: true
      on:
        repo: TAEIN888/lanoa
        branch: master

notifications:
  email:
    recipients:
      - process0823@gmail.com