language: java
jdk:
  - openjdk11

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'

script:  "./mvnw clean package"

before_install:
  - chmod +x mvnw

notifications:
  email:
    recipients:
      - process0823@gmail.com
      -
deploy:
    - provider: s3
      access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
      secret_access_key: $AWS_SECRET_KEY
      bucket: lanoa-deploy
      region: ap-northeast-2
      skip_cleanup: true
      acl: public_read
      wait-until-deployed: true
      on:
        repo: TAEIN888/lanoa
        branch: master